// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    ACheckbox: typeof import('ant-design-vue/es')['Checkbox']
    ADrawer: typeof import('ant-design-vue/es')['Drawer']
    ADropdown: typeof import('ant-design-vue/es')['Dropdown']
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    AInput: typeof import('ant-design-vue/es')['Input']
    AlbumCard: typeof import('./../components/AlbumCard.vue')['default']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    AMenuDivider: typeof import('ant-design-vue/es')['MenuDivider']
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
    AMenuItemGroup: typeof import('ant-design-vue/es')['MenuItemGroup']
    APopconfirm: typeof import('ant-design-vue/es')['Popconfirm']
    APopover: typeof import('ant-design-vue/es')['Popover']
    AProgress: typeof import('ant-design-vue/es')['Progress']
    ASelect: typeof import('ant-design-vue/es')['Select']
    ASelectOption: typeof import('ant-design-vue/es')['SelectOption']
    ASubMenu: typeof import('ant-design-vue/es')['SubMenu']
    ATabPane: typeof import('ant-design-vue/es')['TabPane']
    ATabs: typeof import('ant-design-vue/es')['Tabs']
    DownOutlined: typeof import('@ant-design/icons-vue')['DownOutlined']
    Header: typeof import('./../components/Header.vue')['default']
    Login: typeof import('./../components/Login.vue')['default']
    MvCard: typeof import('./../components/MvCard.vue')['default']
    Nav: typeof import('./../components/Nav.vue')['default']
    Player: typeof import('./../components/Player.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Singer: typeof import('./../components/Singer.vue')['default']
    Skeleton: typeof import('./../components/Skeleton.vue')['default']
    SongCard: typeof import('./../components/SongCard.vue')['default']
    SongListCard: typeof import('./../components/SongListCard.vue')['default']
    SongListItem: typeof import('./../components/SongListItem.vue')['default']
    SongPlayerItem: typeof import('./../components/SongPlayerItem.vue')['default']
  }
}
