// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    ADrawer: typeof import('ant-design-vue/es')['Drawer']
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    AInput: typeof import('ant-design-vue/es')['Input']
    AlbumCard: typeof import('./../components/AlbumCard.vue')['default']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
    AMenuItemGroup: typeof import('ant-design-vue/es')['MenuItemGroup']
    ASubMenu: typeof import('ant-design-vue/es')['SubMenu']
    ATabPane: typeof import('ant-design-vue/es')['TabPane']
    ATabs: typeof import('ant-design-vue/es')['Tabs']
    Header: typeof import('./../components/Header.vue')['default']
    Login: typeof import('./../components/Login.vue')['default']
    MvCard: typeof import('./../components/MvCard.vue')['default']
    Nav: typeof import('./../components/Nav.vue')['default']
    Player: typeof import('./../components/Player.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SongCard: typeof import('./../components/SongCard.vue')['default']
    SongListCard: typeof import('./../components/SongListCard.vue')['default']
    SongPlayerItem: typeof import('./../components/SongPlayerItem.vue')['default']
  }
}
